### ISSUE TITLE
textlintのルールに誤字があります。

### ISSUE THREAD

**Issue by kuri-megane** [kawamataryo/resume#15]
# 課題

textlint `4.2.7.コロン(：)` のルール設定が有効にならない

```
"4.2.7.コロン(:)": false,
```
↓ 特定のルールを無効化してもtextlintで指摘される
```
- レガシーコード: からモダンなフロントエンドへのリファクタリング
# コロン(：)を使用する場合は「全角」で表記します。 (jtf-style/4.2.7.コロン(：))
```

# 原因

`.textlintrc` のルールに誤字がある

```
"4.2.7.コロン(:)": true,      # 誤
"4.2.7.コロン(：)": true,   # 正
```

https://github.com/kawamataryo/resume/blob/master/.textlintrc#L86

# その他

突然のissue、失礼いたします。
職務経歴書作成の参考にさせていただいております。
作業中に間違いを見つけましたので投稿いたします。
GitHubで出す初めてのissueなのでやり方もよくわからずにいますが、ご確認いただけると幸いです。

**Comment by kuri-megane** [comment]
https://github.com/kawamataryo/resume/pull/16 にて、修正のプルリクを発行しました。

**Comment by kawamataryo** [comment]
Issueありがとうございます！
頂いたPRをマージしたのでクローズします！
https://github.com/kawamataryo/resume/pull/16
